### ISSUE TITLE
New Order "FAILED_ORDER_WITH_OPEN_ORDERS"

### ISSUE THREAD

**Issue by iamsasan** [BTCTrader/broker-api-docs#163]
Sometimes when I want create a new order server response error "FAILED_ORDER_WITH_OPEN_ORDERS". 

Please help me what is meaning of this error and how could I solve it.

**Comment by onurgozupek** [comment]
Hi, this error means that your balance is not enough. Most probably you are trying to buy with all of your free balance. But you need to calculate commission amount and deduct it from the "buy" amount. Sometimes, it may be because rounding. Please try deducting a few Satoshi's from the total amount.

**Comment by iamsasan** [comment]
Hi @onurgozupek 
Thanks for your response.
